import React, { useState, useEffect } from 'react';
import { SpeedInsights } from '@vercel/speed-insights/react';
import { Layout } from './components/Layout';
import { Onboarding } from './components/Onboarding';
import { Dashboard } from './components/Dashboard';
import { Chat } from './components/Chat';
import { CheckIn } from './components/CheckIn';
import { Settings } from './components/Settings';
import { UserProfile, View } from './types';
import { ShieldAlert, Trophy, Settings as SettingsIcon, Lock, ChevronRight, Bell, AlertTriangle, CheckCircle } from 'lucide-react';

const App = () => {
  const [currentView, setCurrentView] = useState<View>(View.ONBOARDING);
  const [user, setUser] = useState<UserProfile | null>(null);
  const [showDisclaimer, setShowDisclaimer] = useState(false);

  useEffect(() => {
    const savedUser = localStorage.getItem('titan_user');
    if (savedUser) {
      const parsedUser = JSON.parse(savedUser);
      setUser(parsedUser);
      // If user exists but hasn't consented (legacy users or cleared cache), show disclaimer
      if (!parsedUser.hasConsented) {
        setShowDisclaimer(true);
      } else {
        setCurrentView(View.DASHBOARD);
      }
    } else {
      // New user: show disclaimer before onboarding
      setShowDisclaimer(true);
    }
  }, []);

  const handleDisclaimerAccept = () => {
    if (user) {
      // Existing user accepting new terms
      const updatedUser = { ...user, hasConsented: true };
      setUser(updatedUser);
      localStorage.setItem('titan_user', JSON.stringify(updatedUser));
      setShowDisclaimer(false);
    } else {
      // New user accepting terms before onboarding
      setShowDisclaimer(false);
      setCurrentView(View.ONBOARDING);
    }
  };

  const handleOnboardingComplete = (profile: UserProfile) => {
    const userWithDefaults = {
      ...profile,
      hasConsented: true, // Explicitly set true here as they passed the gate
      notifications: {
        dailyCheckIn: false,
        morningBrief: true,
        workoutReminders: true
      }
    };
    setUser(userWithDefaults);
    localStorage.setItem('titan_user', JSON.stringify(userWithDefaults));
    setCurrentView(View.DASHBOARD);
  };

  const updateUser = (updatedUser: UserProfile) => {
    setUser(updatedUser);
    localStorage.setItem('titan_user', JSON.stringify(updatedUser));
  };

  const renderContent = () => {
    // Safety check: if somehow we are deep in the app but no user (shouldn't happen due to logic above)
    if (!user && currentView !== View.ONBOARDING) return <Onboarding onComplete={handleOnboardingComplete} />;
    
    // Explicit Onboarding Route
    if (currentView === View.ONBOARDING) return <Onboarding onComplete={handleOnboardingComplete} />;

    if (!user) return <Onboarding onComplete={handleOnboardingComplete} />;

    switch (currentView) {
      case View.DASHBOARD:
        return <Dashboard user={user} />;
      case View.CHAT:
        return <Chat user={user} />;
      case View.CHECKIN:
        return <CheckIn user={user} />;
      case View.PROFILE:
        return <ProfileView user={user} setView={setCurrentView} />;
      case View.SETTINGS:
        return <Settings user={user} onBack={() => setCurrentView(View.PROFILE)} onUpdateUser={updateUser} />;
      default:
        return <Dashboard user={user} />;
    }
  };

  // 1. Disclaimer Modal (Highest Priority)
  if (showDisclaimer) {
    return (
      <div className="h-screen bg-black flex items-center justify-center p-6 z-50 fixed inset-0">
        <div className="bg-titan-dark border border-titan-gray rounded-2xl p-6 max-w-sm w-full shadow-2xl relative">
          <div className="flex flex-col items-center text-center space-y-4">
            <div className="p-4 bg-titan-warning/10 rounded-full text-titan-warning ring-1 ring-titan-warning/30">
              <AlertTriangle size={32} />
            </div>
            
            <h2 className="text-xl font-bold text-white uppercase tracking-wide">
              Legal Disclaimer
            </h2>
            
            <div className="text-left bg-titan-black/50 p-4 rounded-xl text-xs text-gray-300 border border-titan-gray/50 space-y-3 leading-relaxed max-h-[40vh] overflow-y-auto">
              <p>
                <strong>Titan Health OS</strong> is an AI-powered lifestyle optimization tool. It is 
                <span className="text-titan-danger font-bold"> NOT </span> a medical device and does not provide medical advice.
              </p>
              <p>
                The workout routines, diet plans, and mental discipline strategies generated by this AI are for informational and educational purposes only.
              </p>
              <p>
                <strong>Agreement:</strong> By clicking "I Understand", you acknowledge that you are using this app at your own risk. You agree to consult a physician before beginning any new exercise or nutrition program. You agree to hold Titan Health OS harmless from any liability.
              </p>
            </div>

            <button 
              onClick={handleDisclaimerAccept}
              className="w-full py-4 bg-white text-black font-bold rounded-xl hover:bg-gray-200 transition-colors active:scale-95 flex items-center justify-center gap-2"
            >
              <CheckCircle size={18} />
              I Understand & Agree
            </button>
            
            <p className="text-[10px] text-titan-muted">
              v1.0.1 Public Release
            </p>
          </div>
        </div>
        <SpeedInsights />
      </div>
    );
  }

  // 2. Onboarding View (No Layout)
  if (currentView === View.ONBOARDING) {
      return (
          <div className="h-screen bg-titan-black text-white max-w-md mx-auto overflow-hidden">
               {renderContent()}
               <SpeedInsights />
          </div>
      )
  }

  // 3. Settings View (No Layout - Fullscreen)
  if (currentView === View.SETTINGS) {
    return (
        <div className="h-screen bg-titan-black text-titan-text max-w-md mx-auto shadow-2xl overflow-hidden relative">
             {renderContent()}
             <SpeedInsights />
        </div>
    );
  }

  // 4. Main App Layout
  return (
    <Layout currentView={currentView} setView={setCurrentView}>
      {renderContent()}
      <SpeedInsights />
    </Layout>
  );
};

// Profile View
interface ProfileViewProps {
  user: UserProfile;
  setView: (view: View) => void;
}

const ProfileView = ({ user, setView }: ProfileViewProps) => (
    <div className="p-4 space-y-8 pt-8">
        <div className="flex items-center gap-4">
            <div className="w-16 h-16 bg-gradient-to-br from-titan-accent to-purple-600 rounded-full flex items-center justify-center text-2xl font-bold text-white">
                {(user.name || 'T').charAt(0).toUpperCase()}
            </div>
            <div>
                <h2 className="text-xl font-bold">{user.name || 'Titan User'}</h2>
                <span className="text-xs bg-titan-gray px-2 py-1 rounded text-titan-muted">Free Plan</span>
            </div>
        </div>

        <div className="bg-gradient-to-r from-yellow-600/20 to-orange-600/20 border border-yellow-600/30 p-6 rounded-2xl relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-20">
                <Trophy size={80} className="text-yellow-500" />
            </div>
            <h3 className="text-lg font-bold text-yellow-500 mb-2">Upgrade to Titan Pro</h3>
            <p className="text-sm text-gray-300 mb-4">Unlock advanced specific diet plans, unlimited AI coaching, and community challenges.</p>
            <button className="w-full bg-yellow-500 hover:bg-yellow-400 text-black font-bold py-3 rounded-xl transition-colors">
                Subscribe ₹199/mo
            </button>
        </div>

        <div className="space-y-3">
            <button 
                onClick={() => setView(View.SETTINGS)}
                className="w-full p-4 bg-titan-dark rounded-xl flex items-center justify-between border border-titan-gray hover:bg-titan-gray/50 transition-colors group"
            >
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-titan-gray rounded-lg group-hover:bg-titan-dark transition-colors">
                         <Bell size={20} className="text-titan-text" />
                    </div>
                    <span className="font-medium">Notification Settings</span>
                </div>
                <ChevronRight size={20} className="text-titan-muted" />
            </button>

            <button className="w-full p-4 bg-titan-dark rounded-xl flex items-center justify-between border border-titan-gray opacity-50 cursor-not-allowed">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-titan-gray rounded-lg">
                        <SettingsIcon size={20} className="text-titan-muted" />
                    </div>
                    <span>Integrations</span>
                </div>
                <Lock size={16} />
            </button>
            
             <button className="w-full p-4 bg-titan-dark rounded-xl flex items-center justify-between border border-titan-gray">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-titan-gray rounded-lg">
                        <ShieldAlert size={20} className="text-titan-danger" />
                    </div>
                    <span>Emergency Mode</span>
                </div>
                <div className="w-8 h-4 bg-titan-gray rounded-full relative"></div>
            </button>
        </div>

        <div className="text-center text-xs text-titan-muted pt-8">
            Titan OS v1.0.1
        </div>
    </div>
);

export default App;